name: Deploy Frontend to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Only trigger when something in the `frontend` changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Change into the frontend folder, install dependencies, and build the project
      - name: Install Dependencies & Build
        run: |
          cd frontend
          yarn install
          yarn build

      # Configure AWS credentials from secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Sync the build output to the S3 bucket
      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/dist s3://karuifeather-cloudresume --delete

      # Invalidate the CloudFront
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
